version: '3.8'

services:
  django:
    build: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - cassandra
    environment:
      - DB_HOST=cassandra
      - DB_NAME=tu_keyspace
      - DB_PORT=9042
      - DB_USER=admin  # Este valor puede variar si usas autenticación
      - DB_PASSWORD=adminpassword  # Este valor puede variar si usas autenticación

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_START_RPC=true
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - CASSANDRA_AUTHENTICATOR=PasswordAuthenticator
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  cassandra_data:
